# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            David Dinh
tagline:          'Web Developer'
description:      'Web Development blog'
url:              http://daviddinh.uk
baseurl:          /

author:
  name:           'David Dinh'
  url:            https://twitter.com/dattdinh

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/daviddinh/
gems:             [jekyll-paginate,
                   jekyll-gist]